### ISSUE TITLE
Оплата не работает при первом вводе некорретных данных

### ISSUE THREAD

**Issue by Nelfimov** [torin-asakura/drum-in#187]
### Описание бага

Если в форму оплаты ввести в первый раз некорректные данные, то последующие исправления формы не активируют кнопку для оплаты.

### Воспроизведение

1. https://drumin.pro/opening-the-rhythm
2. "Начать обучение"
3. Заполнить форму, не прожать чекбокс
4. "Оплатить"
5. Прожать чекбокс
6. "Оплатить"

### Ожидаемое поведение

Форма отправилась, осуществлен редирект на страницу оплаты

### Материалы

https://github.com/user-attachments/assets/463bbf0d-afea-42c2-8839-4ca340ef1b92
https://t.me/c/1057842456/42128/75532

### Данные окружения

Сафари Version 18.1.1 (19619.2.8.111.7, 19619)

**Comment by kirill-ivanovvv** [comment]
@Nelfimov 

не удается воспроизвести баг. 

- браузер на вебкит
- на первом касте делаю как в "Воспроизведение" бага в задаче
- на втором касте сначал ввожу все неправильно затем исправляю и затем форма отправляется

https://github.com/user-attachments/assets/aa76a16e-e228-4343-aed8-340fb9f4efb7


https://github.com/user-attachments/assets/1b053ef0-44db-4596-bf6a-0cb55b09404a

**Comment by Nelfimov** [comment]
Давай добавим простую валидацию формы с поповерами

**Comment by TorinAsakura** [comment]
> Давай добавим простую валидацию формы с поповерами

да ты сам проверил на живом сафари

**Comment by kirill-ivanovvv** [comment]
#### Что сделано:
- поповер при смене фокуса

#### Что дальше:
- разобраться как повесить onClick обработчик на кнопку. сейчас почемуто не работает

#### Актуальная ветка:
- https://github.com/torin-asakura/drum-in/tree/fix/form

**Comment by Nelfimov** [comment]
Релиз упал

**Comment by kirill-ivanovvv** [comment]
> Релиз упал

бандл бампить?

<details>
<summary>log</summary>

```powershell
[operator@archlinux atls_drum-in]$ yarn workspace @landing/renderer-entrypoint prepack
(node:90510) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:90569) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Type Error: Cannot read properties of undefined (reading '/home/operator/work/atls_drum-in/.pnp.cjs')
    at dynamicRequireNoCache (/home/operator/work/atls_drum-in/.yarn/releases/yarn-remote.cjs:134:57670)
    at dynamicRequireFsTime (/home/operator/work/atls_drum-in/.yarn/releases/yarn-remote.cjs:134:58293)
    at Object.dynamicRequire (/home/operator/work/atls_drum-in/.yarn/releases/yarn-remote.cjs:134:58739)
    at /home/operator/work/atls_drum-in/.yarn/releases/yarn-remote.cjs:1256:22463
    at Object.getFactoryWithDefault (/home/operator/work/atls_drum-in/.yarn/releases/yarn-remote.cjs:134:54906)
    at fVe.findPackageLocation (/home/operator/work/atls_drum-in/.yarn/releases/yarn-remote.cjs:1256:22408)
    at /home/operator/work/atls_drum-in/.yarn/releases/yarn-remote.cjs:184:1551
    at Function.from (<anonymous>)
    at kle (/home/operator/work/atls_drum-in/.yarn/releases/yarn-remote.cjs:184:1269)
    at vmt (/home/operator/work/atls_drum-in/.yarn/releases/yarn-remote.cjs:184:1953)
[operator@archlinux atls_drum-in]$ 
``` 

</details>

**Comment by Nelfimov** [comment]
Нет, там старое все

**Comment by Nelfimov** [comment]
Подтверждаю фикс в проде
